name: Checks

on:
  push:
    branches: [master]

jobs:
#  build:
#    name: "Build"
#    runs-on: ubuntu-latest
#    steps:
#      - name: build
#        run: ./gradlew build
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: tests
        run: ./gradlew test

